"""empty message

Revision ID: 994e7728978c
Revises: 
Create Date: 2021-09-09 22:26:44.925140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994e7728978c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movie_id', 'actors', type_='foreignkey')
    op.create_foreign_key(None, 'actors', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actors', type_='foreignkey')
    op.create_foreign_key('movie_id', 'actors', 'movies', ['movie_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
